In [1]:
import pandas as pd
data = pd.read_csv('database.csv')
data

/Users/sdukootu/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Record ID Agency Code                Agency Name       Agency Type  \
0               1     AK00101                  Anchorage  Municipal Police   
1               2     AK00101                  Anchorage  Municipal Police   
2               3     AK00101                  Anchorage  Municipal Police   
3               4     AK00101                  Anchorage  Municipal Police   
4               5     AK00101                  Anchorage  Municipal Police   
5               6     AK00101                  Anchorage  Municipal Police   
6               7     AK00101                  Anchorage  Municipal Police   
7               8     AK00101                  Anchorage  Municipal Police   
8               9     AK00101                  Anchorage  Municipal Police   
9              10     AK00101                  Anchorage  Municipal Police   
10             11     AK00101                  Anchorage  Municipal Police   
11             12     AK00101                  Anchorage  Municipal Police   
12             13     AK00101                  Anchorage  Municipal Police   
13             14     AK00101                  Anchorage  Municipal Police   
14             15     AK00101                  Anchorage  Municipal Police   
15             16     AK00101                  Anchorage  Municipal Police   
16             17     AK00101                  Anchorage  Municipal Police   
17             18     AK00103                     Juneau  Municipal Police   
18             19     AK00106                       Nome  Municipal Police   
19             20     AK00113                     Bethel  Municipal Police   
20             21     AK00118        North Slope Borough     County Police   
21             22     AK00118        North Slope Borough     County Police   
22             23     AK00118        North Slope Borough     County Police   
23             24     AK00118        North Slope Borough     County Police   
24             25     AK00118        North Slope Borough     County Police   
25             26     AK00123                      Kenai  Municipal Police   
26             27     AKASP00        Alaska State Police      State Police   
27             28     AKASP00        Alaska State Police      State Police   
28             29     AKASP00        Alaska State Police      State Police   
29             30     AKASP00        Alaska State Police      State Police   
...           ...         ...                        ...               ...   
638424     638425     WVWSP21     State Police: Kingwood      State Police   
638425     638426     WVWSP24     State Police: Danville      State Police   
638426     638427     WVWSP29   State Police: Morgantown      State Police   
638427     638428     WVWSP29   State Police: Morgantown      State Police   
638428     638429     WVWSP33  State Police: Parkersburg      State Police   
638429     638430     WVWSP39    State Police: Princeton      State Police   
638430     638431     WVWSP49       State Police: Sutton      State Police   
638431     638432     WVWSP52        State Police: Wayne      State Police   
638432     638433     WVWSP52        State Police: Wayne      State Police   
638433     638434     WVWSP53   State Police: Upperglade      State Police   
638434     638435     WVWSP55        State Police: Welch      State Police   
638435     638436     WVWSP55        State Police: Welch      State Police   
638436     638437     WVWSP60   State Police: Williamson      State Police   
638437     638438     WVWSP65                Sp: Hundred      State Police   
638438     638439     WVWSP65                Sp: Hundred      State Police   
638439     638440     WVWSP65                Sp: Hundred      State Police   
638440     638441     WY00101                    Laramie  Municipal Police   
638441     638442     WY00300            Campbell County           Sheriff   
638442     638443     WY01100             Laramie County           Sheriff   
638443     638444     WY01101 

In [3]:
#what are the columns?
data.columns

Index([u'Record ID', u'Agency Code', u'Agency Name', u'Agency Type', u'City',
       u'State', u'Year', u'Month', u'Incident', u'Crime Type',
       u'Crime Solved', u'Victim Sex', u'Victim Age', u'Victim Race',
       u'Victim Ethnicity', u'Perpetrator Sex', u'Perpetrator Age',
       u'Perpetrator Race', u'Perpetrator Ethnicity', u'Relationship',
       u'Weapon', u'Victim Count', u'Perpetrator Count', u'Record Source'],
      dtype='object')

In [4]:
#how many cells in the table?
data.size

15322896

In [5]:
#how many rows?
data.index.size

638454

In [6]:
#whats the row vs col on the table
data.shape

(638454, 24)

In [11]:
data.describe()

Record ID           Year       Incident     Victim Age  \
count  638454.00000  638454.000000  638454.000000  638454.000000   
mean   319227.50000    1995.801102      22.967924      35.033512   
std    184305.93872       9.927693      92.149821      41.628306   
min         1.00000    1980.000000       0.000000       0.000000   
25%    159614.25000    1987.000000       1.000000      22.000000   
50%    319227.50000    1995.000000       2.000000      30.000000   
75%    478840.75000    2004.000000      10.000000      42.000000   
max    638454.00000    2014.000000     999.000000     998.000000   

        Victim Count  Perpetrator Count  
count  638454.000000      638454.000000  
mean        0.123334           0.185224  
std         0.537733           0.585496  
min         0.000000           0.000000  
25%         0.000000           0.000000  
50%         0.000000           0.000000  
75%         0.000000           0.000000  
max        10.000000          10.000000

In [12]:
#Year range from 1980 to 2014
#Incident = 999.0 looks like a placeholder for "unknown/not available"
#victim age = 998.0 looks like a placeholder for "unknown/not available"

In [15]:
data.keys()

Index([u'Record ID', u'Agency Code', u'Agency Name', u'Agency Type', u'City',
       u'State', u'Year', u'Month', u'Incident', u'Crime Type',
       u'Crime Solved', u'Victim Sex', u'Victim Age', u'Victim Race',
       u'Victim Ethnicity', u'Perpetrator Sex', u'Perpetrator Age',
       u'Perpetrator Race', u'Perpetrator Ethnicity', u'Relationship',
       u'Weapon', u'Victim Count', u'Perpetrator Count', u'Record Source'],
      dtype='object')

In [14]:
data[['Year','State','Incident']].pivot_table(index='Year',columns='State',values='Incident',aggfunc='sum')

State  Alabama  Alaska  Arizona  Arkansas  California  Colorado  Connecticut  \
Year                                                                           
1980    1207.0    79.0    854.0     348.0     55509.0     669.0        288.0   
1981    1034.0   145.0    677.0     319.0     38637.0     679.0        261.0   
1982     982.0   178.0    700.0     261.0     43348.0     446.0        277.0   
1983     684.0   129.0    611.0     283.0     37186.0     496.0        205.0   
1984     705.0    88.0    733.0     271.0     33660.0     520.0        172.0   
1985     893.0    73.0    728.0     250.0     34844.0     574.0        181.0   
1986    1088.0    77.0   1096.0     295.0     41000.0     639.0        253.0   
1987     630.0    80.0    900.0     252.0     37718.0     502.0        287.0   
1988     901.0    46.0    920.0     278.0     33003.0     451.0        388.0   
1989    1019.0    67.0   1108.0     349.0     44733.0     338.0        354.0   
1990    1366.0    55.0   1162.0     353.0     56852.0     382.0        381.0   
1991    1463.0    75.0   1307.0     399.0     61791.0     619.0        376.0   
1992   10692.0    70.0   1427.0     395.0     67748.0     629.0        397.0   
1993    1316.0   110.0   1722.0     512.0     62808.0     501.0        479.0   
1994    1603.0    77.0   2940.0     497.0     43384.0     514.0        542.0   
1995    1347.0   112.0   3197.0     424.0     42745.0     619.0        278.0   
1996    1199.0    69.0   2112.0     294.0     30463.0     469.0        307.0   
1997    1065.0   101.0   1976.0     362.0     20254.0     438.0        218.0   
1998     774.0    60.0   2165.0     262.0     12626.0     791.0        239.0   
1999      20.0   106.0   2561.0     203.0     11832.0     858.0        195.0   
2000    1163.0    48.0   1749.0     222.0     17634.0     227.0        161.0   
2001     734.0    49.0   2929.0     602.0     19685.0     300.0        174.0   
2002     601.0    63.0   2488.0    1207.0     23872.0     351.0        122.0   
2003     749.0    69.0   3319.0     299.0     17366.0     409.0        189.0   
2004     502.0    70.0   2755.0     993.0     17046.0     644.0        130.0   
2005     924.0    53.0   2896.0     308.0     16147.0     400.0        159.0   
2006     955.0    68.0   3320.0     435.0     15898.0     344.0        157.0   
2007     929.0    78.0   3143.0     531.0     13089.0     304.0        188.0   
2008     763.0    32.0   1731.0     242.0     10927.0     249.0        234.0   
2009     581.0    55.0   1389.0     241.0      8735.0     263.0        178.0   
2010     255.0    65.0   1432.0     172.0      8032.0     237.0        202.0   
2011       NaN    56.0   1308.0     232.0      9769.0     304.0        211.0   
2012       2.0    59.0   1256.0     296.0      8846.0     282.0        275.0   
2013       2.0    68.0   1539.0     216.0      7695.0     307.0        147.0   
2014       1.0    74.0   1187.0     295.0      6784.0     238.0        122.0   

State  Delaware  District of Columbia   Florida   ...     South Dakota  \
Year                                              ...                    
1980       84.0                1660.0    7002.0   ...              5.0   
1981       54.0                2457.0    7365.0   ...             10.0   
1982       44.0                1956.0    5988.0   ...             18.0   
1983       30.0                1695.0    5799.0   ...             11.0   
1984       27.0                1424.0    4887.0   ...             11.0   
1985       41.0                1073.0    4997.0   ...              9.0   
1986       37.0                1327.0    4667.0   ...             20.0   
1987       37.0                2284.0    5185.0   ...             11.0   
1988       44.0                6535.0       NaN   ...             13.0   
1989       45.0                8591.0       NaN   ...              8.0   
1990       39.0               10163.0       NaN   ...             15.0   
1991       48.0               10338.0       1.0   ...             82.0   
199

In [18]:
import numpy as np
np.unique(data['Victim Age'])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 998])

In [19]:
np.unique(data['Perpetrator Age'])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ' ', '0', '1',
       '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
       '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30',
       '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41',
       '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52',
       '53', '54', '55', '56', '57', '58', '59', '6', '60', '61', '62',
       '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73',
       '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84',
       '85', '86', '87', '88', '89', '9', '9

In [28]:
#what the??? why are there strings in there??! needs cleaning.
clean_data = data

clean_data.loc[clean_data['Perpetrator Age'] ==' ','Perpetrator Age'] = 998
clean_data['Perpetrator Age'] = pd.to_numeric(clean_data['Perpetrator Age'], errors='ignore')
np.unique(clean_data['Perpetrator Age'])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 998, '0', '1',
       '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
       '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30',
       '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41',
       '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52',
       '53', '54', '55', '56', '57', '58', '59', '6', '60', '61', '62',
       '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73',
       '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84',
       '85', '86', '87', '88', '89', '9', '9

In [46]:
#import time
#clean_data1['Month'] = clean_data1['Month'].map(lambda x: time.strftime('%m', time.strptime(x, '%B')))
np.unique(pd.to_numeric(clean_data['Month'], errors='raise'))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
np.unique(clean_data['Crime Type'])

array(['Manslaughter by Negligence', 'Murder or Manslaughter'], dtype=object)

In [48]:
np.unique(clean_data['Victim Sex'])

array(['Female', 'Male', 'Unknown'], dtype=object)

In [49]:
np.unique(clean_data['Perpetrator Sex'])

array(['Female', 'Male', 'Unknown'], dtype=object)

In [50]:
np.unique(clean_data['Victim Count'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
np.unique(clean_data['Victim Race'])

array(['Asian/Pacific Islander', 'Black', 'Native American/Alaska Native',
       'Unknown', 'White'], dtype=object)

In [52]:
np.unique(clean_data['Perpetrator Race'])

array(['Asian/Pacific Islander', 'Black', 'Native American/Alaska Native',
       'Unknown', 'White'], dtype=object)

In [53]:
np.unique(clean_data['Perpetrator Ethnicity'])

array(['Hispanic', 'Not Hispanic', 'Unknown'], dtype=object)

In [54]:
#Ethnicity vs race??
np.unique(clean_data['Victim Ethnicity'])

array(['Hispanic', 'Not Hispanic', 'Unknown'], dtype=object)

In [55]:
np.unique(clean_data['Relationship'])

array(['Acquaintance', 'Boyfriend', 'Boyfriend/Girlfriend', 'Brother',
       'Common-Law Husband', 'Common-Law Wife', 'Daughter', 'Employee',
       'Employer', 'Ex-Husband', 'Ex-Wife', 'Family', 'Father', 'Friend',
       'Girlfriend', 'Husband', 'In-Law', 'Mother', 'Neighbor', 'Sister',
       'Son', 'Stepdaughter', 'Stepfather', 'Stepmother', 'Stepson',
       'Stranger', 'Unknown', 'Wife'], dtype=object)

In [56]:
np.unique(clean_data['Crime Solved'])

array(['No', 'Yes'], dtype=object)

In [67]:
solved_crimes = clean_data[(clean_data['Crime Solved'] == 'Yes') & (clean_data['Victim Count'] >= 2)]

In [68]:
solved_crimes.index.size

10781

In [74]:
relationships = clean_data['Relationship']

from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
labelled_relationships = enc.fit_transform(relationships)

from sklearn.preprocessing import OneHotEncoder
enc1 = OneHotEncoder()
oh = enc1.fit_transform(labelled_relationships)

oh.shape

/Users/sdukootu/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


(1, 638454)

In [ ]:
#a bit of research into the world of serial killers
#http://skdb.fgcu.edu/info.asp
    

In [ ]:
#feature selection - trying out an initial set of features


In [ ]:
from sklearn import metrics
from sklearn.cluster import KMeans
np.random.seed(42)
n_samples, n_features = clean_data.shape
from sklearn.decomposition import PCA
